### ISSUE TITLE
Minecraft not working after using Taurine JB without tweaks

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [Odyssey-Team/Taurine#17] opened 2021-12-18 16:27 UTC
Crash log is here:

Cr4shed:
[cr4shed.txt](https://github.com/Odyssey-Team/Taurine/files/7741591/cr4shed.txt)

**Comment by bukaixyz** [comment] 2022-02-07 12:53
This is not a bug ,you need to hide the jailbreak.

**Comment by admin-elvistrujanovic** [comment] 2022-02-08 00:21
> This is not a bug ,you need to hide the jailbreak.

I tried to hide jailbreak with many tweaks but it didn't work. I also tried to not jailbreak my device after full rootfs restore but the game is still crashing immediately after I open the app. The app is legally installed from Apple App Store.

**Comment by LCD323** [comment] 2022-07-09 18:08
On my iPhone 13, I used filza escaped to get access to modify my iPhone and I changed the persona folder on minecraft and I was able to get capes and I am not jailbroken but my phone turns pink sometimes when I open filza. I am on 15.0.2, do you know how I can prevent this from happening?

**Comment by LCD323** [comment] 2022-07-09 21:23
I had to use filzaescaped 15 and 2 other apps using sideloadly to sign them, and the first time using them, to gain read and write access i had to open the 2 apps and click the buttons to run the scripts. The screen turns pink when i use both apps before rebooting my iphone 13, but if i only use one of them, it gives read and write access and I open filza and now am able to see hidden directories on my phone but like I said earlier, sometimes when I am browsing the phones root file system, if the app is open too long, it will close/crash and about 1/3 of the time instead of closing my screen freezes and then turns pink and then black and then shows the apple logo and turns back on by it self. I am wondering if you know how I can prevent the occassional pink screen crash. It didnt give me boot loop and never has but it crashes sometimes and also I didn't think it would work in the first place since im on ios 15.0.2, but it also doesnt install cydia at the moment so I can only manually edit my phones root system using filza. I don't want to type all day since my hands are starting to hurt, but if you think you know how I can prevent this glitch, please let me know. Thank you for your time.

**Closed** 2022-08-11 09:05 UTC
